// <auto-generated />
using System;
using DbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbConnection.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260923100616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbConnection.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Key")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Operation")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResponseStatusCode")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("Id", "Key", "Operation", "ReservationId", "RequestHash", "ResponseBody", "ResponseStatusCode", "ExpiresAt", "CreatedAt");

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("DbConnection.Domain.Entities.MeetingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Name");

                    b.ToTable("MeetingRooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("847b786f-de7d-47eb-9f0e-843062e436ef"),
                            Name = "Room 1"
                        },
                        new
                        {
                            Id = new Guid("79b5947f-a1aa-49f0-b4b6-5bb23d070c12"),
                            Name = "Room 2"
                        },
                        new
                        {
                            Id = new Guid("312c5953-b9e5-471c-b7bf-fa1d6650f5b1"),
                            Name = "Room 3"
                        },
                        new
                        {
                            Id = new Guid("242c2a00-ae11-46cd-bb0c-b66176f4b569"),
                            Name = "Room 4"
                        });
                });

            modelBuilder.Entity("DbConnection.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MeetingRoomId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRoomId");

                    b.HasIndex("Id", "StartsAtUtc", "EndsAtUtc", "MeetingRoomId", "Status");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DbConnection.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("DbConnection.Domain.Entities.Reservation", "Reservation")
                        .WithMany("IdempotencyRecords")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("DbConnection.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("DbConnection.Domain.Entities.MeetingRoom", "MeetingRoom")
                        .WithMany("AllReservations")
                        .HasForeignKey("MeetingRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingRoom");
                });

            modelBuilder.Entity("DbConnection.Domain.Entities.MeetingRoom", b =>
                {
                    b.Navigation("AllReservations");
                });

            modelBuilder.Entity("DbConnection.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("IdempotencyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
